# Add this to your Docker Compose configuration, or merge it by referencing this file in the COMPOSE_FILE environment
# variable in an env-file.
# Encryption requires a mandatory public key which can be added to the environment file. See Readme.md for more details

volumes:
  backup:

services:
  backup:
    image: ghcr.io/b3partners/backup:latest
    container_name: ${COMPOSE_PROJECT_NAME}-backup
    restart: unless-stopped
    volumes:
      - ${BACKUP_VOLUME_SOURCE:-backup}:/backup
    environment:
      - "SCHEDULE"
      - "LOGGING"
      - "BACKUP_PG"
      - "BACKUP_DIR"
      - "PGHOST=${PGHOST:-db}"
      - "PGPORT"
      - "PGDATABASE"
      - "PGUSER=${PGUSER:-postgres}"
      - "PGPASSWORD=${PGPASSWORD:-postgres}"
      - "STORAGE_BOX"
      - "SFTP_HOST"
      - "SFTP_USER"
      - "SFTP_PATH=${SFTP_PATH:-.}"
      - "SSHPASS"
      - "PG_COMPRESS"
      - "TAR_COMPRESS"
      - "ZSTD_NBTHREADS"
      - "XZ_DEFAULTS"
      - "ENCRYPT"
      - "PUBLIC_KEY"