name: 'Build and Publish image'

concurrency:
  group: ${{ github.workflow }}-${{ ( github.ref == 'refs/heads/main' ) && format('ci-main-{0}', github.sha) || format('ci-main-{0}', github.ref) }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:

jobs:
  build_and_publish:
    name: 'Build and Publish image'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: 'Checkout repository'
        with:
          lfs: true
          fetch-depth: 2

      - name: 'Login to GitHub container registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push latest image'
        run: docker buildx build --tag ghcr.io/b3partners/backup:latest --push .
